runtime: nodejs14
service: default
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
  secure: always
  redirect_http_response_code: 301
  expiration: 10m

- url: /
  static_dir: build
  expiration: 10m
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /(.*)
  static_files: build/index.html
  upload: build/index.html
  secure: always
  redirect_http_response_code: 301
  expiration: 10m